# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Emilian's Brain Dump
tagline:          'The Blog Is Smarter Than The Brain'
description:      ''
url:              http://mercer.github.io
timezone:         Europe/Bucharest

author:
  name:           'Emilian Losneanu'
  url:            https://twitter.com/losneanu

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/poole/hyde
