# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            The Brain Dump
tagline:          'The Blog Is Smarter Than The Brain'
description:      'A random collection of miscellanea'
url:              http://mercer.github.io
timezone:         Europe/Bucharest

author:
  name:           'Emilian Losneanu'
  url:            https://twitter.com/losneanu

paginate:         5

defaults:
  -
  	values:
      layout: "post"
      comments: true
