# Dependencies
markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Deadlock
url:              http://mercer.github.io

author:
  name:           'Emilian Losneanu'
  url:            https://twitter.com/losneanu

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true
